[workspace]
members = [ "jplaw_io", "jplaw_data_types","jplaw_pdf2text"]
resolver = "2"

[workspace.package]
authors = ["Naoki Kaneko <puripuri2100@gmail.com>"]
edition = "2021"
version = "0.2.4"
license = "MIT"
